### ISSUE TITLE
Why did you choose this European license?

### ISSUE THREAD

**Issue by rugk** [enkore/borgcube#21]
Just because I am curious: Why did you switch from [the GPLv2](https://github.com/enkore/borgcube/commit/e1f1423ea0f46c97be47470789b9288a0b7b2574) to the European Union Public License 1.1?

**Comment by enkore** [comment]
The EUPL has approved translations into many languages, the GPL does not. The EUPL is more clear in some points as well.

**Comment by rugk** [comment]
Nice, thanks for your explanation.
